config/routes.rb
Workshops::Application.routes.draw do

  get 'email_templates/docs'
  resources :email_templates

  get "reports/index"

  match "/recent" => "recent#index"
  match "/recent_sessions" => "recent_sessions#index"

  match '/contact',    to: 'static_pages#contact' , :via => :get
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about' , :via => :get
  match '/error',   to: 'static_pages#error'
  match '/workshops/:id/details' => 'workshops#details', :as => 'workshop_details'
  match '/workshops/course_select', :controller=>'workshops', :action => 'course_select', :via => [:get, :post]
  match '/workshops/section_select', :controller=>'workshops', :action => 'section_select', :via => [:get, :post]
  match "/attachments(/*path)", :to => 'attachments#file', :as => 'attachment'
  match "/w/:code", to: 'workshops#short', :as => 'short', :via => :get 

  match '/dash' => 'workshops#dash', :as => 'workshops_dash'

  get 'workshops/session_types'
  get '/workshops/subjects_like'
  get '/workshops/courses_like'
  get '/workshops/sections_like'

  get 'calendars/find_rooms'
  get 'calendars/find_instructors'
  get 'calendars/instructor_calendar'
  get 'calendars/request_token'
  get 'calendars/room_calendar'
  get 'calendars/access'
  get 'calendars/grant_access'
  get 'calendars/revoke_access'

  resources :workshops do
    member do
      get 'copy'
      get 'instructors_like'
      get 'schedule'
      get 'stats'
      get 'statistics'
      get 'evaluation'
      post 'claim'
      post 'claim_show_view'
      post 'save_stats_tab'
      put 'choose_location'
      put 'library_location_required'
      put 'session_type'
      put 'toggle_manage'
      put 'toggle_archive'
      put 'contact_user'
      put 'update_attribute'
    end
    resources :notification_preferences
    resources :comments
    resources :instructor_assignments, :only => [:create, :update, :destroy]
    resources :workshop_events, :only => [:index]
    resources :updates, :only => [:index]
  end
  get 'topics/xeditable_list'
  resources :topics
  resources :locations
  resources :units
  resources :reports
  resources :recent
  resources :session_sub_choices

  get 'topic_categories/choices'
  get 'topic_categories/reorder'
  put 'topic_categories/order'
  resources :topic_categories 

  get "users/uniqname_like"

  resources :sessions, only: [:create, :delete]
  get   'login'  => 'sessions#new', as: :login
  match 'logout' => 'sessions#destroy', as: :logout, via: [:get, :post]
  match 'logout_now' => 'sessions#logout_now', as: :logout_now, via: [:get, :post]

  get 'users/search_by_name'
  get 'users/search_form'
  resources :users do
    member do
      get 'options'
      put 'revise_options'
    end
    resources :comments
    resources :notification_preferences
    resources :updates, :only => [:index, :update]
  end
  resources :evaluations
  resources :registrations

  resources :comments, :only => [:index, :respond] 

  match "/oauth2callback" => "calendars#access"

  root :to => 'workshops#index'

end

app/helpers/workshops_helper.rb
module WorkshopsHelper
  def instructor_list(workshop)
    workshop.instructors.map{|i| h i.display_name}.join("<br/> ").html_safe
  end

  def instructor_ids(workshop)
    workshop.instructors.map(&:id)
  end

  def instructor_names(workshop)
    workshop.instructors.map(&:display_name)
  end

  def short_location_name(workshop)
    workshop.location_name(false)
  end

  def topic_list(workshop)
    workshop.topics.map {|t| h t.title}.join("<br/>").html_safe
  end

  def topic_id_list(workshop)
    list = []
    workshop.topics.each {|t| list << t.id}
    list.to_s
  end

  def details_list(workshop)
    render :partial => 'workshops/details' , :locals  => { :workshop => workshop }
  end

  def contact_user_name(workshop)
    workshop.try(:contact_user).try(:display_name) || "(Unknown)"
  end

  def contact_user_uniqname(workshop)
    workshop.try(:contact_user).try(:uniqname) || "(Unknown)"
  end

  def contact_user_sort_name(workshop)
    workshop.try(:contact_user).try(:sort_name) || "(Unknown)"
  end

  def workshops_statistics_participants(workshop)
    workshop.try(:statistics).try(:participants)
  end

  def workshops_statistics_unit2(workshop)
    workshop.try(:statistics).try(:unit2)
  end

  def workshops_statistics_notes(workshop)
    workshop.try(:statistics).try(:notes)
  end

  def workshops_session_type(workshop)
    workshop.try(:session_type).try(:name)
  end

  def requester_user_name(workshop)
    workshop.try(:requested_by).try(:display_name) || "(Unknown)"
  end

  def requester_user_sort_name(workshop)
    workshop.try(:requested_by).try(:sort_name) || "(Unknown)"
  end

  def contact_user_email(workshop)
    user = workshop.contact_user
    "#{user.uniqname}@umich.edu" if user
  end

  def workshop_scheduled_time(workshop)
    l workshop.scheduled_time_start_time, format: :short_datetime if workshop.try(:scheduled_time_start_time)
  end

  def workshop_session_title(workshop)
    if workshop.title.present?
      link_to(workshop.title, short_url(workshop.id.to_s(36)),
      {:class => "action-links" , :title => 'Open the evaluation for this Library Instruction session', :target => '_blank'})
    end
  end

  def evaluation_link(workshop)
    if workshop.id.present?
      link_to(image_tag("view_eval_results.png"), short_url(workshop.id.to_s(36)),
      {:class => "action-links" , :title => 'Open the evaluation for this Library Instruction session',
        :alt => 'Open the evaluation for this Library Instruction session'})
    end
  end

  def space_out_linebreaks(text)
    if text.nil?
      return ''
    else
      return simple_format(text.gsub(/([\n\f\r])/,' \1'))
    end
  end

  # needed in _details partial
  # FIXME: Delete this once the details partial is removed and we
  #        confirm that nothing else uses it.
  def requested_times(workshop)
    req_times = []
    workshop.requested_times.each do |rt|
      req_times << rt.time_range.display_short_d_long_m.html_safe
    end
    return req_times.join("<br/> ").html_safe
  end

  # NOTE: This is temporary duplication so we can ship performance
  #       improvements for the dashboard without soak testing the
  #       app for uses of the requested_times helper.
  def all_requested_times(workshop)
    workshop.requested_times.map do |t|
      {
        start_time: t.start_time,
        end_time: t.end_time
      }
    end
  end

  # needed for created_at in "Recent Activity" tab and show-view
  def short_day_display(text)
    if text.blank?
    else
      text.strftime("%a, %m/%d/%Y")
    end
  end

  # needed for created_at in "Recent Activity" tab
  def simple_time(datetime_obj)
    str = ""
    unless datetime_obj.nil?
      str = datetime_obj.strftime("%-I:%M %P")
    end
    return str
  end

  def managed_by_name(workshop)
    workshop.try(:managed_by).try(:display_name) || "(None)"
  end

  def managed_by_initials(workshop)
    initials = '  '
    if workshop.managed_by.present?
      names = workshop.try(:managed_by).try(:display_name).split
      if names.length > 0
        initials[0] = names.first[0]
      end
      if names.length > 1
        initials[1] = names.last[0]
      end
    end
    initials
  end

  def active_tab_class(tab_id, active_tab_id = 'review', in_list = true)
    active_tab_class = ''
    if tab_id == active_tab_id
      if in_list
        active_tab_class = "class=active"
      else
        active_tab_class = 'active'
      end
    end
    return active_tab_class
  end

# put the roles in here for now - so just 1 place to define them
  def get_roles()
    return [
      ['requester', 'requester'],
      ['librarian', 'librarian'],
      ['instructor', 'instructor'],
      ['scheduler', 'scheduler'],
      ['admin', 'admin']
    ]
  end

# how many instructors are there for a workshop
  def how_many_instructors(workshop)
    unless workshop.instructor_assignments{:workshop_id}.empty? ||
        # maybe the user_id (instructror's id) was removed somehow - there's an instructor_assignments record but no user
           workshop.instructor_assignments{:user_id}.empty?

      return workshop.instructor_assignments.count
    else
      return 0
    end
  end

# some things we don't need to report on the workshop create event detail
# item passed in is something like 'column_name*value'
  def massage_item(item)
    case item.split('*')[0]
      when 'class_related'
        return "Class Related*" + ( item.split('*')[1] ? 'Yes' : 'No' )
      when 'library_location_required'
        return "Library Location Required*" + ( item.split('*')[1] ? 'Yes' : 'No')
      when 'contact_user_id'
        return "Contact Name*" + User.find((item.split('*')[1]).to_i).try('display_name')
      when 'sub_crs_sec'
        if item.split('*')[1].count('blank') < 3
          return "Subject Course Section* " + item.split('*')[1]
        else
          return ''
        end
      when 'session_type_id'
        st0 = SessionType.find(item.split('*')[1].to_i).name
        return "Session Type*" + st0
      when 'expected_attendance'
        return "Expected Attendance* " +  item.split('*')[1]
      when 'notes'
        return "Notes*" +  item.split('*')[1]
      when 'requester_questions'
        return "Requester question(s)*" +  item.split('*')[1]
      when 'evaluation_id'
        eval_id = item.split('*')[1].to_i
        if eval_id < 1
          return "Evaluation system*Not yet set"
        else
          return "Evaluation system*#{Evaluation.find(eval_id).name}"
        end
      when 'created_at', 'updated_at', 'day', 'start_time', 'end_time', 'course', 'subject', 'section', 'id', 'requested_by_id'
        return ''
    else
      return item
    end
  end

  def workshop_link(workshop)
    link_to(workshop.title, workshop, :class => "workshop-link")
  end

  def stat_link(workshop)
    # the stats link is either not there at all (if today < sched date), or
    # Add Stats (if today >= today and stats not complete) or View Stats (if stats complete)
    # also, has to be 'scheduled' in the first place - so if workshop.day, end_time is nill then no show

    #the workshop has been taught, so can either add (if stats not complete) or view (if completed)
    if today_gt_workshop(workshop)
      if can?(:add_stats, workshop) && !workshop.statistics.completed
        link_to(image_tag("add16.png", :alt => "Add stats for this workshop"), stats_workshop_path(workshop),
         {:class => "action-links", :title => 'Add statistics for this session', :alt => 'Add statistics for this session'})
      elsif can? :read, workshop.statistics
        link_to(image_tag("view16.png", :alt => "View this workshop's stats"), stats_workshop_path(workshop),
         {:class => "action-links", :title => 'View  statistics for this session', :alt => 'View statistics for this session'})
      end
    end
  end

  def manage_link(workshop)
    workshop_join = []
    if workshop.eval_results_url.present?
      paddit = false
      if can?(:unclaim, workshop) || can?(:schedule, workshop)
        paddit = true
        workshop_join << link_to(image_tag("view_eval_results.png", :alt => ""), workshop.eval_results_url,
          { :title => "View Evaluation results for the #{workshop.title} instruction session", :target => "_blank",
            :class => "pull-left"})
      end
    end

    if can? :schedule, workshop
      #to line all 3 things up whether they are there or not, if there isnt an eval results icon, space the initials over more
      if paddit
        workshop_join << "<span class='manage-link'>"
      else
        workshop_join << "<span class='manage-link' style='padding-left:20px'>"
      end
      workshop_join << managed_by_initials(workshop) << "</span>"

      workshop_join << link_to('Manage', schedule_workshop_path(workshop), {:class => "action-links floatright",
        :title => "Manage the #{workshop.title} session request"})
    end
    workshop_join.join.html_safe
  end

  def workshop_action_links(unit)
    workshop_join = []
    workshop_join << manage_link(unit)
    workshop_join << '&nbsp;&nbsp;&nbsp;'
    workshop_join << stat_link(unit)
    workshop_join.join.html_safe
  end

  def claim_link(workshop)
    if workshop.instructors.length >= 1 || cannot?(:claim, workshop)
      instructor_for_table(workshop)
    else
      link_to '#', 'data-url' => workshop_instructor_assignments_path(workshop), :class => "btn btn-success btn-mini claim-workshop-button" do
      'Claim <i class="icon-thumbs-up"></i>'.html_safe
      end
    end
  end

  def details_link(workshop)
    link_to image_tag("info.png", :alt => "Show additional request information"),  '#',  :class => "show-details-button"
  end

  def instructors_all(workshop)
    insts = workshop.instructors
    text = []
    i = 0;
    while i < insts.length
        text << insts[i].display_name
        i +=1
    end
    text.join("<br/>").html_safe
  end

  def instructor_for_table(workshop)
    insts = workshop.instructors
    text = ''
    num_instr = insts.length

app/views/workshops/_requested_dates.html.erb
<div class="row-fluid">
  <dl class="span12 dl-horizontal">
    <dt><%= 'Requested Time'.pluralize(@workshop.requested_times.count) %></dt>
    <% if @workshop.requested_times.nil? || @workshop.requested_times.empty? %>
      <dd>None</dd>
    <% else %>
      <% @workshop.requested_times.each do |rt| %>
      <dd class="button-base row">
        <span class="span7">
          <%= rt.time_range.display_time_range.html_safe %>
        </span>
        <% if can?( :schedule, @workshop ) && @have_google_access && (! @workshop.deleted) %>
          <span >
            <% unless omit_rooms %>
              <span >
                <button class="check-rooms btn btn-mini" type="button" data-action="<%= calendars_find_rooms_path %>" data-day="<%= rt.time_range.data_day %>" data-time0="<%= rt.time_range.data_time0 %>" data-time1="<%= rt.time_range.data_time1 %>" data-workshop-id="<%= @workshop.id %>">ROOMS</button>
              </span>
            <% end %>
            <% unless omit_instructors %>
              <span >
                <button class="check-instructors btn btn-mini" type="button" data-action="<%= calendars_find_instructors_path %>" data-workshop-id="<%= @workshop.id %>" data-day="<%= rt.time_range.data_day %>" data-time0="<%= rt.time_range.data_time0 %>" data-time1="<%= rt.time_range.data_time1 %>" data-workshop-id="<%= @workshop.id %>">INSTRUCTORS</button>
              </span>
            <% end %>
            <% unless omit_choose_time %>
              <span >
                <button class="choose-time btn btn-mini" type="button" data-action="<%= update_attribute_workshop_url(@workshop) %>" data-day="<%= rt.time_range.data_day %>" data-time0="<%= rt.time_range.data_time0 %>" data-time1="<%= rt.time_range.data_time1 %>">CHOOSE</button>
              </span>
            <% end %>
          </span>
          <% if rt.time_range.present? && rt.time_range.valid? %>
            <span style="display:none;" class="choose-duration-minutes"><%= rt.time_range.duration_minutes %></span>
            <span style="display:none;" class="choose-start-time"><%= rt.time_range.start_time.try('as_json') %></span>
            <span style="display:none;" class="choose-end-time"><%= rt.time_range.end_time.as_json %></span>
          <% else %>
            <span style="display:none;" class="choose-duration-minutes"></span>
            <span style="display:none;" class="choose-start-time"></span>
            <span style="display:none;" class="choose-end-time"></span>
          <% end %>
        <% end %>
      </dd>
       <% end %>
    <% end %>
  </dl>
</div>

app/views/workshops/add_comment.html.erb
<!-- app/views/workshops/add_comment.html.erb -->

<h2>Add Comment</h2>

app/views/workshops/copy.html.erb
<!-- app/views/workshops/copy.html.erb -->
<script type="text/javascript">
  var workshops_url = "<%= workshops_url %>";
</script>
<%= render 'layouts/home_button' %>
<h2 class="manage-title">Copy Request</h2>
<p class="alert alert-info"><strong> Revise what needs to be revised and click the "Submit Request" button at the bottom.</strong></p>

<%= form_tag( @submit_form_path, :multipart => true, :method => @submit_form_method ) do |f| %>

  <%= render 'form', { :allow_split_on_request_times => true } %>

  <%= render 'layouts/save_cancel' , :link_path => workshops_path , :submit_text => 'Submit Request' %>
<% end %>
<%= render 'topics-selection' %>

app/views/workshops/index.html.erb
<!-- app/views/workshops/index.html.erb -->
<script type="text/javascript">
  var workshops_url = "<%= workshops_url %>";
  var users_url = "<%= user_url(current_user) %>";
</script>

<div id="dashboard" class="data-content-large">
  <% if can? :add_stats, Workshop %>
    <h1 class = "text-center" style = "margin-bottom:25px">Workshop Dashboard</h1>
  <% else %>
    <h1 class = "text-center" style = "margin-bottom:25px">My Instruction Sessions</h1>
  <% end %>

  <ul id="workshops-filters" class="nav nav-pills">
    <li class="pillbox-label">Filters:</li>
    <%= workshop_filter_button 'Active',        'active',      'All non-archived requests' %>
    <%= workshop_filter_button 'Mine',          'mine',        'Requests made by you or where you are the contact person, or you are the instructor' %>
    <%= workshop_filter_button 'New Requests',  'requested',   'Requests needing attention - no scheduled day, no instructor, no room' %>
    <%= workshop_filter_button 'No Time',       'unscheduled', 'Sessions without a scheduled day or time' %>
    <%= workshop_filter_button 'No Room',       'unbooked',    'Sessions without an assigned room' %>
    <%= workshop_filter_button 'No Instructor', 'unassigned',  'Sessions without an assigned instructor' %>
    <%= workshop_filter_button 'Needs Stats',   'needs_stats', 'Sessions which have been taught where stats have not yet been completed' %>
    <%= workshop_filter_button 'Needs Eval',    'needs_eval',  'Sessions for which an eval has not been completely setup' %>
    <%= workshop_filter_button 'Archived',      'archived',    'Archived (non-active) requests only' %>
    <%= workshop_filter_button 'My Recently Completed', 'recent',    'Sessions you recently conducted' %>

    <% if can? :manage, :all %>
      <%= workshop_filter_button 'Deleted', 'deleted', 'Deleted sessions' %>
    <% end %>
         <%# title: 'Requests made by you or where you are the contact person, or you are the instructor' %>
    </li>
  </ul>

  <% if logged_in? %>
  <div class="well-tzippy">
    <table id="workshops" class="table-striped datatable" data-source="<%= workshops_url(format: "json") %>"
      summary="List of requests for Library Instruction">
      <thead>
        <tr>
          <th data-col="title" class="span4 text-left">Title</th>
          <th data-col="id" class="span1 text-center"><small><em> info</em></small></th>
          <th data-col="instructor_names" class="span4 text-left">Instructor</th>
          <th data-col="scheduled_time_start_time"     class="span3 text-left">Scheduled Time</th>
          <th data-col="short_location_name"     class="span4 text-left">Location</th>
          <th data-col="contact_user_name"     class="span4 text-left">Contact</th>
  <!--         <th data-col="action_links" class="span3"></th> -->
          <th data-col="has_statistics" class="text-left">
            <% if can? :create, Statistics %> <small><em>Stats</em></small></th>
            <% end %>
          <th data-col="managed_by_id" class="span2 text-center">
            <% if can? :archive, Workshop %>  <!-- kind of a cannot, to trap out roles above instructor -->
            <% elsif can? :create, Statistics  %>  <span style="padding-right:5px"><small><em>Eval</em></small></span>
            <% end %> </th>
        </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
  </div>
  <% end %>
</div>

<div id="modal" style="display:none;"></div>

app/views/workshops/show.html.erb
<div class="row-fluid ">
  <div class = "show_page">
    <%= render 'layouts/home_button' %>
    <h2 class="manage-title" style="padding-bottom:10px;">Instruction Request</h2>
    <%= render 'layouts/ws_pager' %>
  </div>
  <div class="toolbar-2nd pull-right show-view-toolbar">

    <% if can? :schedule, @workshop %>
      <%= link_to 'Manage', schedule_workshop_path(@workshop), class: 'btn btn-small btn-link pull-right' %>
    <% end %>

    <% if can_edit_ws(@workshop) %>
      <%= link_to 'Edit', edit_workshop_path(@workshop), class: 'btn btn-small btn-link pull-right' %>

    <% end %>

    <%= link_to "Copy", copy_workshop_path, class: 'btn btn-small btn-link pull-right' %>

    <% if (can? :destroy, @workshop) && (! @workshop.deleted) && @have_google_access %>
    <%= link_to 'Delete', '#', 'data-url' => workshop_path(@workshop), :method => :delete, :class => 'btn btn-small btn-link pull-right ', :confirm => "Are you sure you want to delete this request?" %>
    <% end %> 


    <% if (can? :claim, @workshop) && (! @workshop.deleted)  %>
      <%= link_to '#', 'data-url' => workshop_instructor_assignments_path(@workshop), 'data-next' => workshops_path, :class => "btn btn-small btn-link btn-success pull-right claim-workshop-button", 'data-show-view' => true, :style => (@workshop.instructors.include?(current_user) ? 'display:none;' : '' ) do %>
        <%= t(:Claim) %>
        <%= content_tag(:i, "", :class => "icon-thumbs-up").html_safe %>
      <% end %>
    <% elsif (can? :unclaim, @workshop) && (! @workshop.deleted)  %>
      <%= link_to '#', 'data-url' => workshop_instructor_assignment_path(@workshop, 0), :class => "btn btn-small btn-link btn-success pull-right unclaim-workshop-button", 'data-show-view' => true, :style => (@workshop.instructors.include?(current_user) ? '' : 'display:none;') do %>
        <%= t('Remove me') %>
        <%= content_tag(:i, "", :class => "icon-thumbs-down").html_safe %>
      <% end %>
    <% end %>
  </div>

  <h4>Contact Information</h4>

  <div class="well-tzippy" >
    <div class="row-fluid">
      <dl class="span4 dl-horizontal">
        <dt>Contact</dt>
        <dd><%= contact_user_name(@workshop) %></dd>
      </dl>
      <dl class="offset1 span4 dl-horizontal ">
         <dt>Uniqname</dt>
         <dd><%= contact_user_email(@workshop) %></dd>
       </dl>
    </div>
      <div class="row-fluid">
        <span class="offset2"><small><em>This workshop was requested by </em> <%= requester_user_name(@workshop) %>
              ( <em><%= @workshop.try(:requested_by).try(:uniqname) %>)
                on <%= short_day_display(@workshop.created_at) %> <%= simple_time(@workshop.created_at) %></em> </small>
        </span>

    </div>
  </div>

  <% if ! can_edit_ws(@workshop) %>
    <div class="alert alert-info alert-info-show">
      Scheduling for this session request is in process or complete! If you need to make changes, please
        <%= link_to "EMAIL SCHEDULERS", "#", 'data-url' => new_workshop_comment_url(@workshop, :context => :schedulers), :class => "btn btn-small respond-to-comment-btn" %>
    </div>
  <% end %>


  <h4>Session Information</h4>
  <div class="well-tzippy">
    <%if @workshop.class_related %>
        <em>This is a session being taught for a credit bearing class offered by UM </em>-
        <%= @workshop.subject %>  <%= @workshop.course %>  <%= @workshop.section %>
    <% else %>
        <em>This session is not for a credit bearing class offered by UM</em>
    <% end %>

    <p></p>
    <div class="row-fluid">
      <dl class="span4 dl-horizontal">
        <dt>Course Title</dt>
        <dd><%= @workshop.title %></dd>
      </dl>
      <dl class="offset1 span6 dl-horizontal">
        <dt><%= 'Session Topic'.pluralize(@workshop.topics.count) %></dt>
        <% @workshop.topics.each do |topic| %>
          <dd><%= topic.title %></dd>
        <% end %>
      </dl>
    </div>
    <div class="row-fluid">
      <dl class="span4 dl-horizontal">
        <dt>Expected Attendance</dt>
        <dd ><% unless @workshop.expected_attendance.blank? %> <%= @workshop.expected_attendance %> <% else %>
             <span class='none'>Not specified</span><% end %>
        </dd>
      </dl>
    </div>

    <% if @workshop.deleted %>
      <div class="alert alert-info">
        Note: This workshop session has been deleted!
      </div>
    <% elsif @workshop.archived %>
      <div class="alert alert-info">
        Note: This workshop session has been archived!
      </div>
    <% end %>
  </div>

  <h4>Additional Information</h4>
  <div class="row-fluid">
    <div class="well-tzippy">
      <dl class="dl-horizontal show-form-addtional-info">
        <dt><strong><%= 'Requested Date'.pluralize(@workshop.requested_times.count) %></strong></dt>
        <% @workshop.requested_times.each do |requested_time| %>
          <dd><%= requested_time.time_range.display_short_dm.html_safe %> <small>(<%= requested_time.time_range.duration_minutes.to_i %> min)</small></dd>
        <% end %>

        <dt><strong>Scheduled Date</strong> </dt>
        <% if @workshop.scheduled_time.present? && @workshop.scheduled_time.valid? %>
          <dd><%= @workshop.scheduled_time.display_short_dm %> <small>  (<%= @workshop.scheduled_time.duration_minutes.to_i %> min)</small></dd>
        <% else %>
          <dd><span class='none'>No date chosen yet</span></dd>
        <% end %>

        <dt><strong>Location</strong></dt>
        <% if @workshop.location.nil? && @workshop.location_other.nil? %>
          <dd><span class='none'>No location chosen yet</span></dd>
        <% else %>
          <dd><%= @workshop.location_name(true) %></dd>
        <% end %>

        <dt class="show-instructors"><strong><%= 'Instructor'.pluralize(@workshop.instructors.count) %></strong></dt>
        <% if @workshop.instructors.length > 0 %>
          <% @workshop.instructor_assignments.each do |instructor_assignment| %>
            <dd class="show-instructors">
              <%= instructor_assignment.user.display_name %> (<%= instructor_assignment.user.uniqname %>)
              <% if instructor_assignment.user == current_user %>
                <%= link_to image_tag('delete_16.png', :alt => "Remove yourself as instructor for this workshop"), "#", 'data-instructor-id' => instructor_assignment.user.id, 'data-url' => workshop_instructor_assignment_url(@workshop, instructor_assignment), :class => "remove-instructor", :title => "Remove yourself as instructor for this workshop" %>
              <% end %>
            </dd>
          <% end %>
        <% else %>
          <dd class="show-instructors"><em>No instructors assigned yet</em></dd>
        <% end %>

        <dt><strong>Eval URL for Students</strong> </dt>
        <dd>
          <input type='text' class="span5" id='show-eval-url' value='<%= short_url(@workshop.id.to_s(36)) %>'
            onClick=SelectText('#show-eval-url')  />
          <%= link_to "email URL", "#", 'data-url' => new_workshop_comment_url(@workshop, :context => :instructor_eval_url),
            :class => "btn btn-small respond-to-comment-btn" %>
        </dd>

        <dt><strong><%= 'Attachment'.pluralize(@workshop.attachments.count) %></strong> </dt>
        <% unless @workshop.attachments.blank? %>
          <% @workshop.attachments.each do |attachment| %>
            <dd><%= link_to attachment.attached_file.original_filename ,attachment.attached_file.url  %> <span class="filesize"><%= number_to_human_size(attachment.attached_file.size) %></span> </dd>
        <% end %>
        <% else %> <dd> <span class='none'>None</span> </dd>
        <% end %>

        <dt>Questions or Additional Information</dt>
        <dd >
          <% unless @workshop.notes.blank? %>
            <%= space_out_linebreaks @workshop.notes %>
          <% else %>
           <span class='none'>None</span>
          <% end %>
        </dd>
      </dl>
    </div>

  </div>
</div>

<div id="respond-to-comment-div" class="modal hide fade modal-email" role="dialog" data-toggle="modal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
    <h3 id="add-comment-div-head" tabindex="-1">Send Email</h3>
  </div>
  <div id="comment-form" class="modal-body comment-form">
    <div id="response-div">
    </div>
  </div>
  <div class="modal-footer">
    <button class="btn btn-small" data-dismiss="modal" aria-hidden="true">Cancel</button>
    <button class="save-comments btn btn-info btn-small">Send</button>
  </div>
</div>