config/routes.rb
Workshops::Application.routes.draw do

  get 'email_templates/docs'
  resources :email_templates

  get "reports/index"

  match "/recent" => "recent#index"
  match "/recent_sessions" => "recent_sessions#index"

  match '/contact',    to: 'static_pages#contact' , :via => :get
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about' , :via => :get
  match '/error',   to: 'static_pages#error'
  match '/workshops/:id/details' => 'workshops#details', :as => 'workshop_details'
  match '/workshops/course_select', :controller=>'workshops', :action => 'course_select', :via => [:get, :post]
  match '/workshops/section_select', :controller=>'workshops', :action => 'section_select', :via => [:get, :post]
  match "/attachments(/*path)", :to => 'attachments#file', :as => 'attachment'
  match "/w/:code", to: 'workshops#short', :as => 'short', :via => :get 

  match '/dash' => 'workshops#dash', :as => 'workshops_dash'

  get 'workshops/session_types'
  get '/workshops/subjects_like'
  get '/workshops/courses_like'
  get '/workshops/sections_like'

  get 'calendars/find_rooms'
  get 'calendars/find_instructors'
  get 'calendars/instructor_calendar'
  get 'calendars/request_token'
  get 'calendars/room_calendar'
  get 'calendars/access'
  get 'calendars/grant_access'
  get 'calendars/revoke_access'

  resources :workshops do
    member do
      get 'copy'
      get 'instructors_like'
      get 'schedule'
      get 'stats'
      get 'statistics'
      get 'evaluation'
      post 'claim'
      post 'claim_show_view'
      post 'save_stats_tab'
      put 'choose_location'
      put 'library_location_required'
      put 'session_type'
      put 'toggle_manage'
      put 'toggle_archive'
      put 'contact_user'
      put 'update_attribute'
    end
    resources :notification_preferences
    resources :comments
    resources :instructor_assignments, :only => [:create, :update, :destroy]
    resources :workshop_events, :only => [:index]
    resources :updates, :only => [:index]
  end
  get 'topics/xeditable_list'
  resources :topics
  resources :locations
  resources :units
  resources :reports
  resources :recent
  resources :session_sub_choices

  get 'topic_categories/choices'
  get 'topic_categories/reorder'
  put 'topic_categories/order'
  resources :topic_categories 

  get "users/uniqname_like"

  resources :sessions, only: [:create, :delete]
  get   'login'  => 'sessions#new', as: :login
  match 'logout' => 'sessions#destroy', as: :logout, via: [:get, :post]
  match 'logout_now' => 'sessions#logout_now', as: :logout_now, via: [:get, :post]

  get 'users/search_by_name'
  get 'users/search_form'
  resources :users do
    member do
      get 'options'
      put 'revise_options'
    end
    resources :comments
    resources :notification_preferences
    resources :updates, :only => [:index, :update]
  end
  resources :evaluations
  resources :registrations

  resources :comments, :only => [:index, :respond] 

  match "/oauth2callback" => "calendars#access"

  root :to => 'workshops#index'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_filter :require_login
  skip_before_filter :force_ssl

  def home
  end

  def help
  end
end

app/views/static_pages/about.html.erb
<% provide(:title, 'Instruction and Workshops') %>

<div class="row-fluid">
	<%= render 'layouts/home_button' %>
	<h1 class="text-center" style="margin-top:-35px">Instruction and Workshops</h1>
</div>


<p>
<div class="row">
	<span class="span7">
		<p>
			The University Library has a variety of
			<a href="http://www.lib.umich.edu/instruction-and-workshops" target ='_blank'>
				instructional offerings</a>
			at all levels of research experience and for all subjects, whether you are looking for instruction for yourself, a group, or a class you teach.
		</p>
		<br><p>
			You can request a session by submitting the MLibrary Instruction
		<%= link_to 'request form', new_workshop_path %>.
		</p>
	</span>
	<span style="float:right;margin-top:-100px">
		<%= image_tag("tagcloud.png", alt: "MLibrary Tag cloud", width: "500", height: "400") %>
	</span>
</div>
<p style='padding-top:75px'>
  <em><small>The MLibrary Instruction and Workshop Request System has been developed within the
  <a href="http://www.lib.umich.edu/" target="_blank">University of Michigan Library</a>
    by LTIG &mdash; the Learning Technology Incubation Group for Library Learning & Teaching.</small></em>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<div class="row-fluid">
	<%= render 'layouts/home_button' %>
	<h1 class="text-center" style="margin-top:-35px">Contact Us</h1>
</div>

<p style="margin:40px">
  For questions about or support for training and workshops,
  please contact the MLibrary Instruction coordinators at
  <%= mail_to "mlibrary.instruction@umich.edu" , "MLibrary.Instruction@umich.edu" %>.
</p>

app/views/static_pages/error.html.erb
<% provide(:title, 'Error') %>
<h2>Access Denied</h2>
<p>You do not have permission to view this page.</p>

app/views/static_pages/help.html.erb
<h2>StaticPages#help</h2>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center well-tzippy">
  <h1 class="text-center">MLibrary Instruction Request</h1>
  <h2>Welcome!</h2>
  <p>
  	This is the MLibrary Instruction Request System used to submit and track workshop and instruction sessions
  	taught by MLibrarians. When you login, you can use the 'Request a New Workshop' button to make a new request,
  	and track the request status. MLibrary Instructors also use this system to plan and schedule the requests.
  </p>
  <span>
    <%= image_tag("instruction.gif", alt: "MLibrary Tag cloud", width: "300", height: "200", style: "float:right;margin-left:10px") %>
  </span>
  <p>
		To help us tailor a session to your needs, use the request form to let us know a little bit about your class or group, what type of information you'd like covered, and some possible dates that might work for you. You'll be given a chance to select from a list of topics.If you're not sure what would be right for your class or group and you'd like to talk to a librarian first, <strong>fill out the basic information about your class</strong>, submit your request, and the appropriate person will get in touch with you.
	</p>
	<p>
		When submitting a request for an instructional session, we ask that you <strong>request a session at least two weeks in advance</strong>; you will receive a confirmation usually within one business day of its receipt.
  </p>
  <br><br>
	  <p><%= link_to "Sign in now", login_path, class: "btn btn-primary" %>
	  <em><small>You will be redirected to the University of Michigan Weblogin page where you should use your uniqname to login</small></em>
</p>
</div>