config/routes.rb
Workshops::Application.routes.draw do

  get 'email_templates/docs'
  resources :email_templates

  get "reports/index"

  match "/recent" => "recent#index"
  match "/recent_sessions" => "recent_sessions#index"

  match '/contact',    to: 'static_pages#contact' , :via => :get
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about' , :via => :get
  match '/error',   to: 'static_pages#error'
  match '/workshops/:id/details' => 'workshops#details', :as => 'workshop_details'
  match '/workshops/course_select', :controller=>'workshops', :action => 'course_select', :via => [:get, :post]
  match '/workshops/section_select', :controller=>'workshops', :action => 'section_select', :via => [:get, :post]
  match "/attachments(/*path)", :to => 'attachments#file', :as => 'attachment'
  match "/w/:code", to: 'workshops#short', :as => 'short', :via => :get 

  match '/dash' => 'workshops#dash', :as => 'workshops_dash'

  get 'workshops/session_types'
  get '/workshops/subjects_like'
  get '/workshops/courses_like'
  get '/workshops/sections_like'

  get 'calendars/find_rooms'
  get 'calendars/find_instructors'
  get 'calendars/instructor_calendar'
  get 'calendars/request_token'
  get 'calendars/room_calendar'
  get 'calendars/access'
  get 'calendars/grant_access'
  get 'calendars/revoke_access'

  resources :workshops do
    member do
      get 'copy'
      get 'instructors_like'
      get 'schedule'
      get 'stats'
      get 'statistics'
      get 'evaluation'
      post 'claim'
      post 'claim_show_view'
      post 'save_stats_tab'
      put 'choose_location'
      put 'library_location_required'
      put 'session_type'
      put 'toggle_manage'
      put 'toggle_archive'
      put 'contact_user'
      put 'update_attribute'
    end
    resources :notification_preferences
    resources :comments
    resources :instructor_assignments, :only => [:create, :update, :destroy]
    resources :workshop_events, :only => [:index]
    resources :updates, :only => [:index]
  end
  get 'topics/xeditable_list'
  resources :topics
  resources :locations
  resources :units
  resources :reports
  resources :recent
  resources :session_sub_choices

  get 'topic_categories/choices'
  get 'topic_categories/reorder'
  put 'topic_categories/order'
  resources :topic_categories 

  get "users/uniqname_like"

  resources :sessions, only: [:create, :delete]
  get   'login'  => 'sessions#new', as: :login
  match 'logout' => 'sessions#destroy', as: :logout, via: [:get, :post]
  match 'logout_now' => 'sessions#logout_now', as: :logout_now, via: [:get, :post]

  get 'users/search_by_name'
  get 'users/search_form'
  resources :users do
    member do
      get 'options'
      put 'revise_options'
    end
    resources :comments
    resources :notification_preferences
    resources :updates, :only => [:index, :update]
  end
  resources :evaluations
  resources :registrations

  resources :comments, :only => [:index, :respond] 

  match "/oauth2callback" => "calendars#access"

  root :to => 'workshops#index'

end

app/models/topic_category.rb
class TopicCategory < ActiveRecord::Base
  attr_accessible :name, :order

  has_many :topics, :foreign_key => 'category_id'

  def self.ordered
  	TopicCategory.order(:order, :name).all
  end

end

app/controllers/topic_categories_controller.rb
class TopicCategoriesController < ApplicationController

  load_and_authorize_resource :except => [:name]

  include SimpleDataTables
  accept_data_filter :all, :ordered
  default_data_filter :ordered
  alias_data_mapping :topic_count, :topic_count
  alias_data_mapping :action_links, :category_action_links

  # GET /topic_categories
  # GET /topic_categories.json
  def index
    @head_title = "Topic Categories - #{@head_title}"
    Rails.logger.debug "TopicCategoriesController.index"
    @topic_categories = TopicCategory.ordered

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: mapped_json, 'data-filter' => 'ordered' }
    end
  end

  def choices
    Rails.logger.debug "TopicCategoriesController.choices"
    @choices = []
    TopicCategory.ordered.each do |category|
      unless category.topics.blank?
        category.topics.each do |topic|
          choice = { 'value' => "#{topic.category.id}_#{topic.id}", 'text' => topic.title }
          @choices << choice
        end
      end
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @choices }
    end
  end

  def reorder
    @head_title = "Reorder Topic Categories - #{@head_title}"
    @topic_categories = TopicCategory.ordered

    respond_to do |format|
      format.html # reorder.html.erb
      format.json { render json: @topic_categories }
    end
  end

  def order
    Rails.logger.debug "TopicCategoriesController.update_order #{params}"
    if params[:item].present?
      items = params[:item] 
    end
    Rails.logger.debug "TopicCategoriesController.update_order #{items}"
    if items.present?
      index = 1
      items.each.with_index do |item, index|
        TopicCategory.find(item.to_i).update_attribute :order, index + 1
      end
    end

    respond_to do |format|
      format.html { redirect_to @topic_category, notice: "We're working on saving the new order" }
      format.json { render json: mapped_json, 'data-filter' => 'ordered' }
    end
  end

  # GET /topic_categories/1
  # GET /topic_categories/1.json
  def show
    @head_title = "Topic Category - #{@head_title}"
    @topic_category = TopicCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic_category }
    end
  end

  # GET /topic_categories/new
  # GET /topic_categories/new.json
  def new
    @head_title = "New Topic Category - #{@head_title}"
    @topic_category = TopicCategory.new
    @categories = TopicCategory.ordered
    @submit_form_path = topic_categories_path
    @submit_form_method = 'post'
    Rails.logger.debug "TopicCategoriesController.new #{@submit_form_method} #{@submit_form_path}"
 
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic_category }
    end
  end

  # GET /topic_categories/1/edit
  def edit
    @head_title = "Edit Topic Category - #{@head_title}"
    @topic_category = TopicCategory.find(params[:id])
    @submit_form_path = topic_category_path(@topic_category)
    @submit_form_method = 'put'
    Rails.logger.debug "TopicCategoriesController.edit #{@submit_form_method} #{@submit_form_path}"
  end

  # POST /topic_categories
  # POST /topic_categories.json
  def create
    @topic_category = TopicCategory.new(params[:topic_category])
    if params[:insert_after].present?
      insert_after = params[:insert_after].to_i
      TopicCategory.ordered.reverse_each do |category|
        if insert_after == category.id
          @topic_category.order = category.order + 1
          break
        else
          category.update_attribute :order, category.order + 1
        end
      end
    end

    respond_to do |format|
      if @topic_category.save
        format.html { redirect_to topic_categories_path, notice: 'Topic category was successfully created.' }
        format.json { render json: @topic_category, status: :created, location: @topic_category }
      else
        format.html { render action: "new" }
        format.json { render json: @topic_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topic_categories/1
  # PUT /topic_categories/1.json
  def update
    @topic_category = TopicCategory.find(params[:id])

    respond_to do |format|
      if @topic_category.update_attributes(params[:topic_category])
        format.html { redirect_to topic_categories_path, notice: 'Topic category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topic_categories/1
  # DELETE /topic_categories/1.json
  def destroy
    @topic_category = TopicCategory.find(params[:id])
    @topic_category.destroy

    respond_to do |format|
      format.html { redirect_to topic_categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/topic_categories_helper.rb
module TopicCategoriesHelper
  def category_action_links(category)
    can?(:update, category) ? link_to(image_tag("edit16.png"), edit_topic_category_path(category),
    	{:class => "action-links" , :title => 'Edit information about this Category',  :alt => 'Edit information about this Category'}) : ''
  end

  def topic_count(category)
  	category.topics.count
  end

end

app/views/topic_categories/_form.html.erb
<!-- app/views/topic_categories/_form.html.erb -->

<%= form_tag(@submit_form_path, :method => @submit_form_method) do |f| %>
  <% if @topic_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic_category.errors.count, "error") %> prohibited this topic_category from being saved:</h2>

      <ul>
      <% @topic_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="well-tzippy">
    <h2>Topic Category</h2>

    <div class="row-fluid">
      <dl class="span4 dl-horizontal">
        <dt class='required-field' >Name</dt>
        <dd><%= text_field_tag "topic_category[name]", @topic_category.name, :id => 'topic.name' , :class => 'input-xlarge', :required => true %></dd>
      </dl>
    </div>
    <% unless @categories.blank? %>
      <div class="row-fluid">
        <dl class="dl-horizontal">
          <dt><%= label_tag "insert_after", 'Insert after' %><dt>
          <dd>
            <%= select_tag( "insert_after", options_from_collection_for_select(@categories, :id, :name, @categories.last.id), :id => 'insert_after' ) %>
          </dd>
        </dl>
      </div>
    <% end %>
  </div>


  <%= render 'layouts/save_cancel' , :link_path => topic_categories_path, :submit_text => 'Save' %>

<% end %>

app/views/topic_categories/edit.html.erb
<!-- app/views/topic_categories/edit.html.erb -->

<div  class="data-content data-content-small">
<%= render 'layouts/home_button' %>
<h1 class="manage-title">Edit Topic Category</h1>

<%= render 'form' %>
</div>

app/views/topic_categories/index.html.erb
<!-- app/views/topic_categories/index.html.erb -->

<div  class="data-content data-content-small">
<%= render 'layouts/home_button' %>
<h1 class = "manage-title">Topic Categories</h1>

<% if can? :create, TopicCategory %>
  <div class="btn-toolbar toolbar-2nd pull-right">
    <%= link_to "Add a new Category", new_topic_category_path, :class => 'btn btn-link btn-small pull-right'%>
    <%= link_to "Reorder", topic_categories_reorder_path, :class => 'btn btn-link btn-small pull-right'%>
  </div>
<% end %>
<br><br>
<div class="well-tzippy">

  <table id="categories" class="table-striped datatable" data-source="<%= topic_categories_url(format: "json") %>"
    summary="List of Topic Categories used to categorize topics">
    <thead>
      <tr>
        <th data-col="name"  class="span5">Name</th>
        <th data-col="topic_count"  class="span1 text-center">Topics</th>
        <th data-col="order"  class="span1 text-center">Order</th>
        <th data-col="action_links" class="span1"></th>
      </tr>
    </thead>
    <tbody>
    </tbody>
   </table>

</div>
</div>

app/views/topic_categories/new.html.erb
<!-- app/views/topic_categories/new.html.erb -->

<div  class="data-content data-content-small">
<%= render 'layouts/home_button' %>
<h1 class = "manage-title">New Topic Category</h1>

<%= render 'form' %>
</div>

app/views/topic_categories/reorder.html.erb
<!-- app/views/topic_categories/index.html.erb -->
<div  class="data-content data-content-medium">
<%= render 'layouts/home_button' %>
<h1 class = "manage-title">Reorder Topic Categories</h1>

<div class="well-tzippy">
  <p>
  	Drag and drop categories within the list to change the order.
  </p>

  <ul class="category-reorder" id="category-reorder" data-url="<%= topic_categories_order_url %>" >
  	<% @topic_categories.each do |category| %>
		<li id="item_<%= category.id %>" data-id="<%= category.id %>" class="ui-state-default"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span><%= category.name %></li>
    <% end %>
  </ul>

</div>

<div class="btn-toolbar">
  <%= link_to "Done", topic_categories_path, :class => 'btn btn-mini btn-primary' %>
</div>
</div>

app/views/topic_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @topic_category.name %>
</p>


<%= link_to 'Edit', edit_topic_category_path(@topic_category) %> |
<%= link_to 'Back', topic_categories_path %>