config/routes.rb
Workshops::Application.routes.draw do

  get 'email_templates/docs'
  resources :email_templates

  get "reports/index"

  match "/recent" => "recent#index"
  match "/recent_sessions" => "recent_sessions#index"

  match '/contact',    to: 'static_pages#contact' , :via => :get
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about' , :via => :get
  match '/error',   to: 'static_pages#error'
  match '/workshops/:id/details' => 'workshops#details', :as => 'workshop_details'
  match '/workshops/course_select', :controller=>'workshops', :action => 'course_select', :via => [:get, :post]
  match '/workshops/section_select', :controller=>'workshops', :action => 'section_select', :via => [:get, :post]
  match "/attachments(/*path)", :to => 'attachments#file', :as => 'attachment'
  match "/w/:code", to: 'workshops#short', :as => 'short', :via => :get 

  match '/dash' => 'workshops#dash', :as => 'workshops_dash'

  get 'workshops/session_types'
  get '/workshops/subjects_like'
  get '/workshops/courses_like'
  get '/workshops/sections_like'

  get 'calendars/find_rooms'
  get 'calendars/find_instructors'
  get 'calendars/instructor_calendar'
  get 'calendars/request_token'
  get 'calendars/room_calendar'
  get 'calendars/access'
  get 'calendars/grant_access'
  get 'calendars/revoke_access'

  resources :workshops do
    member do
      get 'copy'
      get 'instructors_like'
      get 'schedule'
      get 'stats'
      get 'statistics'
      get 'evaluation'
      post 'claim'
      post 'claim_show_view'
      post 'save_stats_tab'
      put 'choose_location'
      put 'library_location_required'
      put 'session_type'
      put 'toggle_manage'
      put 'toggle_archive'
      put 'contact_user'
      put 'update_attribute'
    end
    resources :notification_preferences
    resources :comments
    resources :instructor_assignments, :only => [:create, :update, :destroy]
    resources :workshop_events, :only => [:index]
    resources :updates, :only => [:index]
  end
  get 'topics/xeditable_list'
  resources :topics
  resources :locations
  resources :units
  resources :reports
  resources :recent
  resources :session_sub_choices

  get 'topic_categories/choices'
  get 'topic_categories/reorder'
  put 'topic_categories/order'
  resources :topic_categories 

  get "users/uniqname_like"

  resources :sessions, only: [:create, :delete]
  get   'login'  => 'sessions#new', as: :login
  match 'logout' => 'sessions#destroy', as: :logout, via: [:get, :post]
  match 'logout_now' => 'sessions#logout_now', as: :logout_now, via: [:get, :post]

  get 'users/search_by_name'
  get 'users/search_form'
  resources :users do
    member do
      get 'options'
      put 'revise_options'
    end
    resources :comments
    resources :notification_preferences
    resources :updates, :only => [:index, :update]
  end
  resources :evaluations
  resources :registrations

  resources :comments, :only => [:index, :respond] 

  match "/oauth2callback" => "calendars#access"

  root :to => 'workshops#index'

end

app/models/unit.rb
class Unit < ActiveRecord::Base
  attr_accessible :name, :active

  scope :active, -> {
    where active: true
  }

  scope :archived, -> {
    where active: false
  }

end

app/controllers/units_controller.rb
class UnitsController < ApplicationController

  include SimpleDataTables
  accept_data_filter :all, :active, :archived
  alias_data_mapping :action_links, :unit_action_links

  default_data_filter :active

  def index
    @head_title = "Unit Name Choices - #{@head_title}"
    respond_to do |format|
      format.html
      format.json { render json: mapped_json }
    end
  end

  def show
    @head_title = "Unit Choice - #{@head_title}"
    @unit  = Unit.find(params[:id])
  end

  def edit
    @head_title = "Edit Unit Choice - #{@head_title}"
    @unit = Unit.find(params[:id])
    @submit_form_path = unit_path(@unit)
    @submit_form_method = 'put'

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @unit }
    end
  end

  def name
    @unit = Unit.find params[:id]
     name = params[:value]
    @unit.update_attribute 'name', name

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json =>  @unit.to_json }
    end
  end

  def create
    @unit = Unit.new(params[:unit])

    respond_to do |format|
      if @unit.save
        format.html { redirect_to units_path, notice: 'New Unit choice was successfully created.' }
        format.json { render json: @unit, status: :created, unit: @unit }
      else
        format.html { render action: "new" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @head_title = "New Unit Choice - #{@head_title}"
    @unit =  Unit.new
    @submit_form_path = units_path
    @submit_form_method = 'post'

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @unit }
    end
  end

  def update
    @unit = Unit.find(params[:id])

    respond_to do |format|
      if @unit.update_attributes(params[:unit])
        format.html { redirect_to units_path, notice: 'Unit choice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @unit = Unit.find params[:id]
    @unit.destroy

    respond_to do |format|
      format.html { redirect_to units_path, :notice => "Unit choice was successfully deleted." }
      format.json { render json: @unit }
    end
  end

   def destroy
    @unit = Unit.find params[:id]
    @unit.destroy

    respond_to do |format|
      format.html { redirect_to units_path, :notice => "Unit choice was successfully deleted." }
      format.json { render json: @unit }
    end
  end

end

app/helpers/units_helper.rb
module UnitsHelper

  def delete_unit_link(unit)
    can?(:update, unit) ? link_to(image_tag("delete_16.png"), unit_path(unit), {
          method:     "delete",
          controller: "units" ,
          confirm:    "Are you really really sure you want to delete the  #{unit.name}  unit choice?",
          alt:        'Delete the unit choice',
          title:      'Delete the unit choice' } ) : ' '
  end

  def edit_unit_link(unit)
    can?(:update, unit) ? link_to(image_tag("edit16.png"), edit_unit_path(unit),
      {:class => "action-link", :title => 'Edit this Unit name',  :alt => 'Edit this Unit name'}) : ''
  end

  def unit_action_links(unit)
    edit_unit_link(unit) + '&nbsp&nbsp&nbsp'.html_safe + delete_unit_link(unit)
  end
end

app/views/units/_form.html.erb
<!-- app/views/units/_form.html.erb -->

  <%= form_tag( @submit_form_path, :multipart => true, :method => @submit_form_method ) do |f| %>

<div class="well-tzippy">
  <br>
  <div class="row-fluid">
    <dl class="span4 dl-horizontal">
      <dt class='required-field' >Name</dt>
      <dd><%= text_field_tag "unit[name]", @unit.name, :id => 'unit.name' , :class => 'input-xlarge', :required => true %></dd>
    </dl>
  </div>
  <div class="row-fluid">
    <dl class="span4 dl-horizontal">
      <dt title = 'Inactive unit choices do not show up for selection'>
        Active Choice</dt>
      <dd title = 'Inactive unit choices do not show up for selection'><%= check_box('unit', 'active') %></dd>
    </dl>
  </div>

  <span class="required-field required-field-note "></span>
  <br>
</span>
</div>

<%= render 'layouts/save_cancel' , :link_path => units_path, :submit_text => 'Save' %>

<% end %>

app/views/units/edit.html.erb
<!-- app/views/units/edit.html.erb -->

<div  class="data-content data-content-small">
<%= render 'layouts/home_button' %>
<h1 class = "manage-title">Edit Unit Choice</h1>

<%= render 'form' %>
</div>

app/views/units/index.html.erb
<!-- app/views/units/index.html.erb -->
<div class="data-content data-content-small">
  <%= render 'layouts/home_button' %>
  <h1 class = "manage-title">Unit Name Choices</h1>

  <div class="btn-toolbar toolbar-2nd pull-right">
    <%= link_to "Add a Unit Name", new_unit_path, :class => 'btn btn-link btn-small pull-right'%>
    </div>

  <ul id="units-filters" class="nav nav-pills filter-list">
    <li class="pillbox-label">Filters: </li>
    <%= filter_button 'All',      'all',      'All Unit names' %>
    <%= filter_button 'Active',   'active',   'Only active Unit names', true %>
    <%= filter_button 'Inactive', 'archived', 'Only in-active Unit names'    %>
  </ul>

  <div class="well-tzippy">
    <table id="units" class="table-striped datatable" data-source="<%= units_url(format: "json") %>"
      summary="List of Unit choices available for selection when entering stats">
      <thead>
        <tr>
          <th data-col="name"         class="span4">Name</th>
          <th data-col="active"       class="span1 active-label">Active</th>
          <th data-col="action_links" class="span2 actions-label"></th>
        </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
  </div>
</div>

app/views/units/new.html.erb
<!-- app/views/units/new.html.erb -->

<div  class="data-content data-content-small">
<%= render 'layouts/home_button' %>
<h1 class = "manage-title">New Unit Choice</h1>

<%= render 'form' %>
</div>